### ISSUE TITLE
Page edit() does not seem to modify page

### ISSUE THREAD

**Issue by mboldin** [ucfopen/canvasapi#139]
I tried to use page.edit(title='New Title')  and page.edit(body='New Body')
but no changes were uploaded.  I think this code under Page in page'py  should not be using 'return  self'  and instead use a requester  Also the purpose of super() is not clear

```
 def edit(self, **kwargs):
        """
        Update the title or the contents of a specified wiki
        page.
        :calls: `PUT /api/v1/courses/:course_id/pages/:url \
        <https://canvas.instructure.com/doc/api/pages.html#method.wiki_pages_api.update>`_
        :rtype: :class:`canvasapi.course.Course`
        """
        response = self._requester.request(
            'PUT',
            '{}s/{}/pages/{}'.format(self.parent_type, self.parent_id, self.url),
            _kwargs=combine_kwargs(**kwargs)
        )
        page_json = response.json()
        page_json.update({'course_id': self.course_id})
        super(Page, self).set_attributes(page_json)

        return self
```

**Comment by Thetwam** [comment]
According to the [Canvas documentation for editing a page](https://canvas.instructure.com/doc/api/pages.html#method.wiki_pages_api.update), the parameter for editing a page's title is `wiki_page[title]` (not `title`), and `wiki_page[body]` (not `body`) for editing the body.

To achieve the same effect with `canvasapi`, you can pass a dictionary as `wiki_page`:

- To edit the title:
  ```python
  page.edit(wiki_page={'title': 'New Title'})
  ```
- To edit the body:
  ```python
  page.edit(wiki_page={'body': 'New Body'})
  ```
- To edit both simultaneously:
  ```python
  page.edit(wiki_page={'title': 'New Title', 'body': 'New Body'})
  ```

The use of `super` updates the object in-place rather than returning a new one. We do, however, return the updated object as well (hence `return self`).

That said, I noticed the return type docstring is incorrect (it actually returns a `Page`, not a `Course), so we will fix that.

**Comment by Thetwam** [comment]
Aside from the docstring fix, there doesn't appear to be any action items for us. Closing this one.

If you have any other problems or questions, please continue to make issues or drop us a line on the [UCF Open Source Slack](https://ucf-open-slackin.herokuapp.com/) in the `#canvasapi` channel.

Thanks for your contributions! 😄
