### ISSUE TITLE
Assignment Overrides

### ISSUE THREAD

**Issue by Thetwam** [ucfopen/canvasapi#216]
We're missing coverage for Assignment Overrides. Add coverage for the following endpoints:

- [x] [List assignment overrides](https://canvas.instructure.com/doc/api/assignments.html#method.assignment_overrides.index)
- [x] [Get a single assignment override](https://canvas.instructure.com/doc/api/assignments.html#method.assignment_overrides.show)
- [x] [Redirect to the assignment override for a group](https://canvas.instructure.com/doc/api/assignments.html#method.assignment_overrides.group_alias)
- [x] [Redirect to the assignment override for a section](https://canvas.instructure.com/doc/api/assignments.html#method.assignment_overrides.section_alias)
- [x] [Create an assignment override](https://canvas.instructure.com/doc/api/assignments.html#method.assignment_overrides.create)
- [x] [Update an assignment override](https://canvas.instructure.com/doc/api/assignments.html#method.assignment_overrides.update)
- [x] [Delete an assignment override](https://canvas.instructure.com/doc/api/assignments.html#method.assignment_overrides.destroy)
- [x] [Batch retrieve overrides in a course](https://canvas.instructure.com/doc/api/assignments.html#method.assignment_overrides.batch_retrieve)
- [x] [Batch create overrides in a course](https://canvas.instructure.com/doc/api/assignments.html#method.assignment_overrides.batch_create)
- [x] [Batch update overrides in a course](https://canvas.instructure.com/doc/api/assignments.html#method.assignment_overrides.batch_update)

**Comment by eelsirhc** [comment]
Can you give an example of the usage? This code doesn't work for me (assuming a valid assignment `va` and student `vs`
```
va.create_override(student_ids=[vs], due_at=datetime(2019,1,2,12,34))
```

instead returning an error
```
BadRequest: {"errors":["one of student_ids, group_id, or course_section_id is required"]}
```

If I manually construct the POST following the [Canvas documentation](https://github.com/instructure/canvas-lms/blob/master/app/controllers/assignment_overrides_controller.rb) I need to construct this

```
va.create_override(**{"assignment_override[student_ids]":[vs],
                                    "assignment_override[due_at]":datetime.datetime(2019,1,2,12,34)})
```

The keywords need the 'assignment_override' prefix, but you can't make them simple keywords anymore because of the square brackets in their name.

**Comment by jessemcbride** [comment]
@eelsirhc Your call should look something like this:

```
override = assignment.create_override(
      assignment_override={
          'student_ids': [1, 2, 3],
          'title': 'New Assignment Override'
     }
)
```

Check out our documentation on [keyword arguments](https://canvasapi.readthedocs.io/en/latest/keyword-args.html#nested-parameters) (in particular, the section on nested parameters). The gist of it is that when Canvas expects parameters of the form `foo[bar]`, we can treat them like dictionaries where `foo` is the name of the dictionary and `bar` is a key within it. Instead of passing keyword arguments to methods like `assignment_override[student_ids]=[1, 2, 3]` (which will throw an invalid syntax error), you pass in a dictionary where the keyword argument name matches what Canvas expects. Then, a method called [combine_kwargs](https://github.com/ucfopen/canvasapi/blob/develop/canvasapi/util.py#L29) transforms the keyword argument into the correct form to be sent to Canvas.

This is probably the trickiest part of the library to master, but once you get the hang of it, you'll notice that it's applicable to pretty much every endpoint. If you're ever unsure of how a particular call should be structured, you can always take a look at the test for that method (in this case, https://github.com/ucfopen/canvasapi/blob/develop/tests/test_assignment.py#L30).

Feel free to drop by the #canvasapi channel on our [Slack](https://ucf-open-slackin.herokuapp.com/) if you have any more questions :).

**Comment by jonathan-taylor** [comment]
I seem to be having some problem with creating assignment overrides (and maybe just the API itself). I have an assignment I want to assign to a particular `course_section_id`. So, I tried the following

```
a.create_override(course_section_id=Py_section.id)
```

Resulting in

```
BadRequest: {"errors":["one of student_ids, group_id, or course_section_id is required"]}
```

I also tried `a.create_override(course_section_id=[Py_section.id])`
The section is valid (I see it on the web API as well):

```
In [75]: Py_section
Out[75]: Section(_requester=<canvasapi.requester.Requester object at 0x106bf1850>, id=237379, course_id=187177, name=Python, start_at=None, end_at=None, created_at=2024-05-29T22:22:18Z, created_at_date=2024-05-29 22:22:18+00:00, restrict_enrollments_to_section_dates=None, nonxlist_course_id=None, sis_section_id=None, sis_course_id=None, integration_id=None)
```

**Comment by jonathan-taylor** [comment]
I also tried the `kwarg` approach using `override={'course_section_id':Py_section_id}` with same error, BUT then I looked at the Canvas docs and saw that I should use `assignment_override={'course_section_id':Py_section_id}`. I can see now how to set different things in the API -- the method names of `canvasapi` aren't identical to the names in the API.
