### ISSUE TITLE
Investigate GitHub Actions

### ISSUE THREAD

**Issue by Thetwam** [ucfopen/canvasapi#445]
We've been using TravisCI for a while now, but I'd like us to take a look at GitHub Actions and see if it suits our purposes.

Motivations:

- Simplify workflow by removing third-party services (Travis and possibly Coveralls)
- Evaluate GitHub Actions for other projects (particularly, internal private repos on GitHub)
- See if there are any additional features we can leverage that Travis doesn't provide

**Comment by Thetwam** [comment]
https://travis-ci.org is going dark at the end of this year, and https://travis-ci.com has some strange pricing shenanigans and issues with acquiring credits for open source. We need to expedite this transition to Actions.

**Comment by jonespm** [comment]
Not sure if you'd worked on this yet, but I got a Github actions started here: https://github.com/jonespm/canvasapi/actions

Just bring over the file from https://github.com/jonespm/canvasapi/tree/develop/.github/workflows

Still TODO:

* Because the ruby is older (2.5.0), I tried switching mdl to markdownlint but that is failing the checks since it probably needs markdown-style.rb translated over. It might be also be possible to get ruby updated so mdl can install, or find another alternative?

* It doesn't do the slack notification or deploy steps. It doesn't look like Slack might [require another action? ](https://github.com/marketplace/actions/slack-notify). Deploy can be done I just didn't add that.

* I didn't set up secrets on this fork for Coveralls to work. This is related to this guide: https://docs.github.com/en/actions/reference/authentication-in-a-workflow

Everything else **looks** like it passes as Travis did.

**Comment by Thetwam** [comment]
@jessemcbride has a branch where he did an initial pass as well.

https://github.com/jessemcbride/canvasapi/tree/issue/445-github-actions

Gonna try to take at what you guys have this week - hopefully get a workable solution deployed.

**Comment by jonespm** [comment]
Cool I didn't see that this was being worked on. Looks like they're pretty similar which is good!

Looks like they used a Github action for the MDL check and I didn't realize that you can adjust it to trigger on the branch. I'd probably have both the but push and pull_request these are at least getting the checks running again. 

```
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
```


You can group the checks into whichever steps you like, and I'm not sure if the default flake8 args are appropriate either (it passes fine without them)

Thanks!
