### ISSUE TITLE
API entry used by `course.get_users()`?

### ISSUE THREAD

**Issue by lsloan** [ucfopen/canvasapi#464]
I see in the documentation that `course.get_users()` uses the `/api/v1/courses/:course_id/search_users` API entry.

Why use that entry rather than `/api/v1/courses/:course_id/users`?

**Comment by Thetwam** [comment]
`Course.get_users` is one of the oldest methods in the library. Looking through `git blame` and old commits (like 5 years back!), it looks like we initially had `search_term` as an optional argument instead of allowing it to be passed as an arbitrary keyword argument. I can't be sure, but I imagine the decision to use the search endpoint instead is related to that.

That said, it seems like the two endpoints are functionally identical, at least as near as I can tell. If you're aware of a reason to use one over the other, I'd be willing to revisit the method.

**Comment by lsloan** [comment]
I thought I'd ask because before I tried `canvasapi`, I was using the `users` API entry in my own code.  When I saw that this package uses the `search_users` API entry instead, I decided to find out why.  As you wrote, they seem to be identical now.

I'll ask on the Canvas Community forum and see what they have to say about it.

**Comment by Thetwam** [comment]
Closing for now. If new information about the endpoints comes to light, feel free to reopen

**Comment by lsloan** [comment]
I've posted a question on the Canvas Community at (https://community.canvaslms.com/t5/Question-Forum/REST-API-quot-courses-course-id-users-quot-or-quot-courses/m-p/443313/highlight/true#M151887).
