### ISSUE TITLE
Input parameters to `edit`

### ISSUE THREAD

**Issue by tomeichlersmith** [ucfopen/canvasapi#513]
This is great and fits my needs exactly. I have one question that is best illustrated by an example.

Let's say `a` is an `Assignment` that I have retrieved from some `Course`. I would expect to be able to
```python
>>> a.edit(canvas_assignment_parameter = new_value)
```
But I have to
```python
>>> a.edit(assignment = {'canvas_assignment_parameter' : new_value})
```

Why is that? Couldn't you update `Assignment.edit` so that you can do the first option?

```python
        response = self._requester.request(
            "PUT",
            "courses/{}/assignments/{}".format(self.course_id, self.id),
            _kwargs=combine_kwargs(assignment = **kwargs),
        )
```
Or is there something I'm misunderstanding about `Assignment.edit`?

(I know this question could apply to a lot of the different canvas objects, I'm just using an example where frequent `edit`s are likely.)

### Current Code for `Assignment.edit` for Reference

https://github.com/ucfopen/canvasapi/blob/2ac9979d17979932a3f43eb8737b7648566c1c68/canvasapi/assignment.py#L59-L77

**Comment by Thetwam** [comment]
Hey @tomeichlersmith,

This is an intentional design decision of CanvasAPI. It is our way of handling more complex parameters, such as `assignment[name]`. Our [Keywords Arguments documentation](https://canvasapi.readthedocs.io/en/stable/keyword-args.html) explains how CanvasAPI handles complex parameters (that `combine_kwargs` function you see is doing quite a bit of heavy lifting).

The short version is that some Canvas endpoints include characters that would be invalid argument names. For example, the [Edit an assignment API](https://canvas.instructure.com/doc/api/assignments.html#method.assignments_api.update) requires `assignment[name]`, `assignment[position]`, `assignment[submission_types][]`, etc. These parameters use square brackets, which are invalid arguments in Python. When Instructure uses that format, they're essentially grouping parameters into objects, so we opted to use dictionaries for a similar effect.

The nice thing about this is that you only have to type the `assignment` keyword once, and can just pass in a dictionary of the things you want to change:

```python
assignment.edit(
    assignment={
        "name": "Assignment Name",
        "position": 1,
        "submission_types": ["online_upload", "online_text_entry"],
        "grading_type": "percent",
        "published": True,
    }
)
```

I agree it can be strange and annoying to use this format when every single parameter starts with `assignment`, but this is how Instructure has decided to format this particular endpoint. If you take a look around the API docs, you'll see lots of different styles. For example, the [Create a new course API](https://canvas.instructure.com/doc/api/courses.html#method.courses.create) uses a similar `course[value]` format for some parameters, but also has other bare parameters like `offer` and `enroll_me`. Rather than try to create specialized parameter handling for each of the hundreds of endpoints, we created a generic solution (`combine_kwargs`) that can handle all the formats that Instructure uses throughout the API.

I highly recommend you read through our [Keyword Arguments documentation](https://canvasapi.readthedocs.io/en/stable/keyword-args.html) to see how to use the different parameter types.

I hope that provides some insight! If you have any further questions, please feel free to re-open the issue, create a [discussion post](https://github.com/ucfopen/canvasapi/discussions), or send us a message on the [UCF Open Slack](https://ucf-open-slackin.herokuapp.com/) in the `#canvasapi` channel.

**Comment by tomeichlersmith** [comment]
Thank you for the explanation! I was not aware of the parameters (like `offer` and `enroll_me`) that are not wrapped by a keyword like `assignment` or `course`. Now that these unwrapped parameters exist, this solution makes the most sense.
