### ISSUE TITLE
Formatting Standardization

### ISSUE THREAD

**Issue by jessemcbride** [ucfopen/canvasapi#68]
Consider using EditorConfig to establish consistent style.

See PR #67 for discussion on this, as well as [EditorConfig's](http://editorconfig.org/) official site.

**Comment by jessemcbride** [comment]
Following some internal discussion, this doesn't seem necessary. Running flake8 in our testing environment locally and with Travis seems sufficient.

**Comment by jessemcbride** [comment]
@Thetwam I'd like to revisit this if we add black as a dependency for code formatting.

**Comment by Thetwam** [comment]
Since @jessemcbride resurrected this issue, I'll just use it as a place to talk about standardizing formatting in general.

The library that Jesse mentioned (`black`) is a super cool auto-formatter:

- https://www.mattlayman.com/blog/2018/python-code-black/
- https://black.readthedocs.io/en/stable/

I've been playing with it over the last week and am really impressed. I would definitely like to use it in our project.

Due to the sheer volume of files it will touch, we'll have to time integrating it completely into the workflow such that we don't disrupt active development. In the meantime, I've been quietly using it on a case-by-case basis when reviewing PRs. 

I think I'll throw together a WIP PR to explore what integrating it into our workflow entails.

**Comment by Thetwam** [comment]
@jessemcbride Now that we have `black` as part of our workflow, are you okay with re-closing this issue?

**Comment by jessemcbride** [comment]
Yeah, `black` fixes this. Closing.
