### ISSUE TITLE
return type of Course.get_full_discussion_topic()

### ISSUE THREAD

**Issue by jackrsteiner** [ucfopen/canvasapi#83]
I'm struggling to understand the return of `get_full_discussion_topic()`. I would greatly appreciate if someone would give an example of how you might parse the output? The same question applies to `DiscussionTopic.list_topic_entries()`.

The endpoint `GET /api/v1/courses/:course_id/discussion_topics/:topic_id/view` natively returns a json string, which at least can be easily made into a dictionary. What can I do with the DiscussionTopic object type? Why was this chosen?

Thanks!

**Comment by Thetwam** [comment]
Hey @jackrsteiner!

I took a look at the two endpoints you asked about. They are both returning `DiscussionTopic` objects, but that appears to be a mistake.

`get_full_discussion_topic()` should probably actually return a `dict`, as you said. In the future, if we address #56, that dict would automatically convert `participants` to `User` objects. The entries in `view` would get a similar treatment.

`list_topic_entries()` should probably return something like a `DiscussionEntry` object rather than a `DiscussionTopic`.

Looking at other discussion-related endpoints, it appears there are several instances of `DiscussionTopic` objects being returned when it should really be an entry object. We will look into fixing this.

**Comment by jackrsteiner** [comment]
@Thetwam,

Awesome, thanks for this clarification. That makes so much more sense. I'll take a closer look at #56.
